### ISSUE TITLE
Remove hipchat support

### ISSUE THREAD

**Issue by eheydrick** [eheydrick/aws-cleaner#25]
Hipchat is dead. Remove all support for it.

- [ ] hipchat gem dep
- [ ] config option
- [ ] `notify_hipchat` method

**Comment by majormoses** [comment]
Should we make a minor release with a deprecation message?

**Comment by eheydrick** [comment]
I'm tempted to just rip it out since hipchat is totally dead as of February. The API endpoint doesn't even resolve in DNS anymore.
https://blog.developer.atlassian.com/atlassian-slack-partnership/
