### ISSUE TITLE
Question regarding getting Hipchat to work

### ISSUE THREAD

**Issue by majormoses** [eheydrick/aws-cleaner#5]
So if I follow the logic correctly then (hip|slack) chat will only be called if you have a webhook you want to call first is that right? What is the rationale behind this? Using the base functionality (removing from chef and sensu) it seems like you should be able to notify (hip|slack) chat without any extra setup (beyond the sqs queue and the CW alarms which would be out of scope here. I feel like I am missing something very obvious...

Here is my config:

```
:aws:
  # rely on IAM for creds but still need to set region
  :region: 'us-west-2'
:sqs:
  :queue: 'https://sqs.us-west-2.amazonaws.com/<REDACTED>/dev-aws-cleaner'
:sensu:
  :url: 'http://10.55.250.8:4567'
:chef:
  :url: 'https://<REDACTED>/organizations/dev'
  :client: 'ip-10-55-250-156.us-west-2.compute.internal'
  :key: '/etc/aws-cleaner/chef-client.pem'
:hipchat:
  :api_token: '<REDACTED>'
  :room: 'Alerts'
  :enable: true
```

**Comment by eheydrick** [comment]
Notifying chat is supposed to happen even without webhooks. Your config looks right. I added webhooks later on and it's possible I screwed something up. I'm going to try to repro w/ that config.

**Comment by majormoses** [comment]
OK I figured it out reading through code that it basically only calls chat if there was a 202, successfully removes, or fails to remove. As we already had a process to de-provision it was silently doing nothing. When disabling that shutdown de-provision script I have verified that it does send hipchat messages.

**Comment by majormoses** [comment]
I think we might want to document the behavior as it might throw someone off, thoughts?

**Comment by majormoses** [comment]
was also thinking we might want to enhance this to optionally log to a file as I imagine most people would run this backgrounded as a service

**Comment by eheydrick** [comment]
Cool, glad you got it notifying. Logging could definitely be improved. I run it under upstart and the logs go to /var/log/upstart/aws-cleaner.log. Perhaps an option to log to a file or stdout.

**Comment by majormoses** [comment]
@eheydrick gonna close this out as hipchat is working. I am not sure what should be added as far as doc goes.
