### ISSUE TITLE
Feature Request: alert when node exists in aws but is not bootstrapped in chef or sensu

### ISSUE THREAD

**Issue by majormoses** [eheydrick/aws-cleaner#6]
This is kind of the reverse scenario of the original intention, basically if a machine fails to bootstrap to chef but is in an auto scale group it could sit there as wasted resources. I would like to propose having something to check back that it is present in chef and if not alert via hip/slack. I can probably take a stab at doing it but wanted to see what your thoughts are on this.

This is the general concept: 
When a machine has a state of saying "running" we have a queue message fired off. We accept a delay option and basically check the message if its older than delay and if so we check if the machine is present in chef and if not then we fire an alert.

**Comment by eheydrick** [comment]
I like the idea and I think that's useful functionality. Not sure if it belongs in aws-cleaner or not as I'd prefer to have it do one thing.

**Comment by majormoses** [comment]
@eheydrick  I was thinking that it would be its own binary in the same project, how do you feel about that? I think that they are trying to accomplish the same goal which is keeping your aws account clean of unusable instances from a chef and sensu perspective. And with the similarities it makes sense to abstract out a lot of the logic into a library to avoid duplication of code.

**Comment by eheydrick** [comment]
+100 on moving logic into a library. I've been meaning to refactor that out, there's no good reason to keep it in the main app. I like the idea of a separate app using common lib code.

**Comment by majormoses** [comment]
refactor work started: #9

**Comment by majormoses** [comment]
@eheydrick I would like to start working on this here: https://github.com/majormoses/aws-watcher but need a release made so I can use the common libs. Any chance I could get you to make a release?

**Comment by eheydrick** [comment]
Yes, will get a release out.

**Comment by eheydrick** [comment]
2.1.0 is live on rubygems.
